export const HANDLE_STATES = "HANDLE_STATES";
/* login action */
export const STORE_USER = "STORE_USER";
export const STORE_PASS = "STORE_PASS";
export const HANDLE_LOG_OUT = "HANDLE_LOG_OUT";
export const HANDLE_LOG_IN_SUBMIT = "HANDLE_LOG_IN_SUBMIT";
export const HANDLE_LOG_IN_SUBMIT_SUCCESS = "HANDLE_LOG_IN_SUBMIT_SUCCESS";
export const HANDLE_LOG_IN_SUBMIT_FAILED = "HANDLE_LOG_IN_SUBMIT_FAILED";
export const HANDLE_LOGGED_IN_COOKIE = "HANDLE_LOGGED_IN_COOKIE";
/* list get */
export const HANDLE_DATA_LOAD = "HANDLE_DATA_LOAD";
export const HANDLE_DATA_LOAD_SUCCESS = "HANDLE_DATA_LOAD_SUCCESS";
export const HANDLE_DATA_LOAD_FAILED = "HANDLE_DATA_LOAD_FAILED";
export const TOGGLE_IS_GETTING_MORE = "TOGGLE_IS_GETTING_MORE";
/* list add */
export const TOGGLE_ADD_SCREEN = "TOGGLE_ADD_SCREEN";
export const HANDLE_SCAN_DATA = "HANDLE_SCAN_DATA";
export const HANDLE_SUBMIT_SCAN_DATA = "HANDLE_SUBMIT_SCAN_DATA";
export const HANDLE_SUBMIT_SCAN_DATA_SUCCESS =
  "HANDLE_SUBMIT_SCAN_DATA_SUCCESS";
export const HANDLE_SUBMIT_SCAN_DATA_FAILED = "HANDLE_SUBMIT_SCAN_DATA_FAILED";
